# Generated by Django 4.1.3 on 2022-11-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isinprogress', models.BooleanField(db_column='isInProgress')),
                ('startdate', models.DateField(db_column='startDate')),
                ('finishdate', models.DateField(blank=True, db_column='finishDate', null=True)),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('isinsured', models.BooleanField(db_column='isInsured')),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('isspecific', models.BooleanField(db_column='isSpecific')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Автопарк',
                'verbose_name_plural': 'Список автомобилей',
                'db_table': 'carlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='firstName', max_length=32)),
                ('lastname', models.CharField(db_column='lastName', max_length=32)),
                ('phone', models.CharField(max_length=12)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OngoingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departuredate', models.DateField(blank=True, db_column='departureDate', null=True)),
                ('arrivaldate', models.DateField(blank=True, db_column='arrivalDate', null=True)),
                ('iscompleted', models.BooleanField(db_column='isCompleted')),
            ],
            options={
                'verbose_name': 'Активный рейс',
                'verbose_name_plural': 'Активные рейсы',
                'db_table': 'ongoing_passage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdamaged', models.BooleanField(db_column='isDamaged')),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Стоянка',
                'verbose_name_plural': 'Стоянки',
                'db_table': 'parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departuredate', models.DateField(blank=True, db_column='departureDate', null=True)),
                ('arrivaldate', models.DateField(blank=True, db_column='arrivalDate', null=True)),
                ('iscompleted', models.BooleanField(db_column='isCompleted')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'db_table': 'passage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(db_column='bankName', max_length=100)),
                ('bankaccount', models.CharField(db_column='bankAccount', max_length=100)),
                ('bik', models.CharField(blank=True, max_length=100, null=True)),
                ('kpp', models.CharField(blank=True, max_length=100, null=True)),
                ('inn', models.CharField(blank=True, max_length=100, null=True)),
                ('ks', models.CharField(blank=True, max_length=100, null=True)),
                ('rs', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
                'db_table': 'prop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('isworking', models.BooleanField(blank=True, db_column='isWorking', null=True)),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Работники',
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False, 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
