# Generated by Django 4.1.3 on 2022-12-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0002_application_branch_car_cargo_carlist_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsView',
            fields=[
                ('payment_type', models.CharField(db_column='payment_type', max_length=20, primary_key=True, serialize=False)),
                ('payment_ru', models.TextField(db_column='payment_ru')),
                ('average', models.FloatField(db_column='average')),
            ],
            options={
                'verbose_name': 'Средний чек по способу оплаты',
                'verbose_name_plural': 'Средние чеки по способам оплаты',
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
